const router = require('express').Router()
let Player = require('../models/player.model')
let PlayerSession = require('../models/playerSession.model')

/*
Player information:
1. Player ID (use object id generated by mongodb)
2. Full name
3. Email
4. Password
5. Avatar
6. Settings (auto log-in)
7. Battle history (array, store one object id for each battle)

const playerSchema = new Schema({
  playerId: { type: Number, required: true },
  fullName: { type: String, required: true },
  email: { type: String, required: true },
  password: { type: String, required: true },
  playerAvatarId: { type: String, required: true }
})
*/

// Get the owner of the session's player id and the hasEnded field.
router.route('/session').get((req, res) => {
  // get player id data from the token.
  PlayerSession.find({ _id: req.query.token })
    .then(sessionData => {
      if (sessionData.length != 1) {
        res.status(400).json('Error: Invalid')
      } else {
        res.json({
          playerId: sessionData[0].playerId,
          hasEnded: sessionData[0].hasEnded
        })
      }
    })
})

// Query one player from database.
router.route('/query').get((req, res) => {
  // get player data by its player id
  Player.find({ _id: req.query.playerId })
    .then(playerData => {
      if (playerData.length != 1) {
        res.status(400).json('Error: Invalid')
      } else {
        res.json({
          fullName: playerData[0].fullName,
          email: playerData[0].email,
          playerAvatarId: playerData[0].playerAvatarId
        })
      }
    })
})

// For registration.
router.route('/signup').post((req, res) => {
  const newPlayer = new Player()

  newPlayer.fullName = req.body.name.trim()
  newPlayer.email = req.body.email.toLowerCase().trim()
  newPlayer.password = newPlayer.generateHash(req.body.password)
  newPlayer.playerAvatarId = req.body.avatar

  newPlayer.save()
    .then(player => res.json(player._id))
    .catch(err => res.status(400).json('Error: ' + err))
})

// For login.
router.route('/login').post((req, res) => {
  const email = req.body.email.toLowerCase().trim()
  const password = req.body.password

  Player.find({ email: email })
    .then(playerData => {
      if (playerData.length != 1) {
        res.status(400).json('Error: Invalid')
      } else {
        const player = playerData[0]
        if (!player.validPassword(password)) {
          res.status(400).json('Error: Invalid')
        }

        const playerSession = new PlayerSession()
        playerSession.playerId = player._id
        playerSession.save()
          .then(token => res.json({
            tokenId: token._id
          }))
          .catch(err => res.status(400).json('Error: ' + err))
      }
    })
})

// For logout
router.route('/logout').get((req, res) => {
  // set value of 'hasEnded' attribute to true.
  PlayerSession.findOneAndUpdate({
    _id: req.query.token,
    hasEnded: false
  }, {
    $set: {
      hasEnded: true
    }
  }, (err, doc, res2) => {
    if (err) {
      res.status(400).json('Error: ' + err)
    } else {
      res.json('Session has successfully ended.')
    }
  })
})

// Update one player info. Find by player id.
router.route('/update/:id').post((req, res) => {
  // update player info by id
})


module.exports = router