const router = require('express').Router()
let Player = require('../models/player.model')

/*
Player information:
1. Player ID (use object id generated by mongodb)
2. Full name
3. Email
4. Password
5. Avatar
6. Settings (auto log-in)
7. Battle history (array, store one object id for each battle)

const playerSchema = new Schema({
  playerId: { type: Number, required: true },
  fullName: { type: String, required: true },
  email: { type: String, required: true },
  password: { type: String, required: true },
  playerAvatarId: { type: Number, required: true }
})
*/

router.route('/').get((req, res) => {
  // get all players' data
  Player.find({})
  .then(playerData => res.json(playerData))
  .catch(err => res.status(400).json('Error: ' + err))
})

// For registration.
router.route('/add').post((req, res) => {
  // add new player into database
  const newPlayer = new Player()

  newPlayer.fullName = req.body.name
  newPlayer.email = req.body.email
  newPlayer.password = newPlayer.generateHash(req.body.password)
  newPlayer.playerAvatarId = Number(req.body.avatar)

  // const fullName = req.body.name
  // const email = req.body.email
  // const password = req.body.password
  // const playerAvatarId = Number(req.body.playerAvatarId)

  // const newPlayer = new Player({
  //   fullName,
  //   email,
  //   password,
  //   playerAvatarId
  // })

  newPlayer.save()
    .then((player) => res.json(player._id))
    .catch(err => res.status(400).json('Error: ' + err))
})

router.route('/update/:id').post((req, res) => {
  // update player info by id
})

module.exports = router