const mongoose = require('mongoose')

const Schema = mongoose.Schema

/*
Enemy information:
1. Enemy ID (use object id generated by mongodb)
2. Enemy name
3. Action Tendency
4. Weak Attack Tendency
5. Strong Attack Tendency
6. Enemy weak attack action ID
7. Enemy strong attack action ID
*/

const enemySchema = new Schema({
  enemyName: { type: String, required: true },

  enemyActionRate: { type: Number, required: true },
  enemyWeakAtkRate: { type: Number, required: true },
  enemyStrongAtkRate: { type: Number, required: true },

  enemyWeakAtkId: { type: String, required: false, default: 0 },
  enemyStrongAtkId: { type: String, required: false, default: 1 },
})

const Enemy = mongoose.model('Enemy', enemySchema)

module.exports = Enemy