const mongoose = require('mongoose')
const bcrypt = require('bcrypt')

const Schema = mongoose.Schema

/*
Player information:
1. Player ID (use object id generated by mongodb)
2. Full name
3. Email
4. Password
5. Avatar
6. Settings (auto log-in)
7. Battle history (array, store one object id for each battle)
*/

const playerSchema = new Schema({
  fullName: { type: String, required: true },
  email: { type: String, required: true },
  password: { type: String, required: true },
  playerAvatarId: { type: Number, required: true }
})

playerSchema.methods.generateHash = function(password) {
  return bcrypt.hashSync(password, bcrypt.genSaltSync(8), null)
}

playerSchema.methods.validPassword = function(password) {
  return bcrypt.compareSync(password, this.password)
}

const Player = mongoose.model('Player', playerSchema)

module.exports = Player